manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: hsgw
      url-base: https://github.com/hsgw
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    # ZMK 本体。公式 app/west.yml を取り込む
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml

    # PMW3610 ドライバ（保守が進んでいるフォークを利用）
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main

    # センサー回転機能（ハンズオン中のモジュール）
    - name: zmk-feature-sensor_rotation
      remote: hsgw
      revision: main

    # RGB LED status widget
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

  self:
    path: config
